"""Public inference API."""

from .confidence import (
    ConfidenceAssessment,
    ConfidenceTier,
    PredictionWarning,
    WarningCode,
    WarningSeverity,
    assess_prediction_confidence,
)
from .fighter_lookup import (
    AmbiguousFighterError,
    DuplicateSnapshotError,
    FighterCandidate,
    FighterIdentityMismatchError,
    FighterLookup,
    FighterLookupError,
    FighterLookupResult,
    FighterNotFoundError,
    FighterSnapshot,
    LookupStatus,
    SnapshotUnavailableError,
    coerce_date,
    normalize_fighter_id,
    normalize_name,
)
from .predictor import (
    DivisionSpec,
    FeatureConstructionError,
    FightPrediction,
    FightPredictor,
    InferenceError,
    InvalidModelOutputError,
    MatchupContext,
    OrientationPrediction,
    SameFighterError,
    UnsupportedMatchupError,
    build_matchup_features,
    refresh_dynamic_snapshot,
    resolve_division,
)

__all__ = [
    "AmbiguousFighterError",
    "ConfidenceAssessment",
    "ConfidenceTier",
    "DivisionSpec",
    "DuplicateSnapshotError",
    "FeatureConstructionError",
    "FightPrediction",
    "FightPredictor",
    "FighterCandidate",
    "FighterIdentityMismatchError",
    "FighterLookup",
    "FighterLookupError",
    "FighterLookupResult",
    "FighterNotFoundError",
    "FighterSnapshot",
    "InferenceError",
    "InvalidModelOutputError",
    "LookupStatus",
    "MatchupContext",
    "OrientationPrediction",
    "PredictionWarning",
    "SameFighterError",
    "SnapshotUnavailableError",
    "UnsupportedMatchupError",
    "WarningCode",
    "WarningSeverity",
    "assess_prediction_confidence",
    "build_matchup_features",
    "coerce_date",
    "normalize_fighter_id",
    "normalize_name",
    "refresh_dynamic_snapshot",
    "resolve_division",
]
